module.exports.ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST";
module.exports.ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";
module.exports.ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL";

module.exports.PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
module.exports.PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
module.exports.PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

module.exports.CLEAR_ERRORS = "CLEAR_ERRORS";
