module.exports.ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST";
module.exports.ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS";
module.exports.ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL";

module.exports.CLEAR_ERRORS = "CLEAR_ERRORS";
