module.exports.LOGIN_REQUEST = "LOGIN_REQUEST";
module.exports.LOGIN_SUCCESS = "LOGIN_SUCCESS";
module.exports.LOGIN_FAIL = "LOGIN_FAIL";

module.exports.REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
module.exports.REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
module.exports.REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

module.exports.LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
module.exports.LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
module.exports.LOAD_USER_FAIL = "LOAD_USER_FAIL";

module.exports.LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
module.exports.LOGOUT_FAIL = "LOGOUT_FAIL";

module.exports.UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
module.exports.UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
module.exports.UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
module.exports.UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

module.exports.UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
module.exports.UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
module.exports.UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
module.exports.UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

module.exports.FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
module.exports.FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
module.exports.FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

module.exports.NEW_PASSWORD_REQUEST = "NEW_PASSWORD_REQUEST";
module.exports.NEW_PASSWORD_SUCCESS = "NEW_PASSWORD_SUCCESS";
module.exports.NEW_PASSWORD_FAIL = "NEW_PASSWORD_FAIL";

module.exports.CLEAR_ERRORS = "CLEAR_ERRORS";
